import { DashboardLoadingState } from "@/components/dashboard/dashboard-states"
import { ContentShell } from "@/components/layout/content-shell"
import { RouteLoadingLifecycle } from "@/components/navigation/route-loading-state"

export default function DashboardsLoading() {
  return (
    <>
      <RouteLoadingLifecycle />
      <ContentShell
        title="Dashboards"
        description="Review Azure DevOps project health and the stakeholder value generated by iTestFlow."
      >
        <DashboardLoadingState label="Preparing your dashboard" cards={5} />
      </ContentShell>
    </>
  )
}
