import { DashboardLoadingState } from "@/components/dashboard/dashboard-states"
import { ContentShell } from "@/components/layout/content-shell"

export default function DashboardsLoading() {
  return (
    <ContentShell
      title="Dashboards"
      description="Review Azure DevOps project health and the stakeholder value generated by iTestFlow."
    >
      <DashboardLoadingState label="Preparing your dashboard" cards={5} />
    </ContentShell>
  )
}
