import { ContentShell } from "@/components/layout/content-shell"
import { DashboardsClient } from "@/components/dashboard/dashboard-client"

export default function DashboardsPage() {
  return (
    <ContentShell
      title="Dashboards"
      description="Review Azure DevOps project health and the stakeholder value generated by iTestFlow."
    >
      <DashboardsClient />
    </ContentShell>
  )
}
