import type { Metadata } from "next"
import { ContentShell } from "@/components/layout/content-shell"

export const metadata: Metadata = { title: "Dashboards" }
import { DashboardsClient } from "@/components/dashboard/dashboard-client"

export default function DashboardsPage() {
  return (
    <ContentShell
      title="Dashboards"
      description="Review Azure DevOps project health and the stakeholder value generated by iTestFlow."
      maxWidth="dashboard"
    >
      <DashboardsClient />
    </ContentShell>
  )
}
