"use client";

import { AlertTriangle, BarChart3, BriefcaseBusiness, RefreshCw, TrendingUp } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";

import { DashboardFilters, defaultDashboardFilters, type DashboardFilterState } from "@/components/dashboard/dashboard-filters";
import { DashboardKpiGrid, ReleaseReadinessCard } from "@/components/dashboard/dashboard-summary";
import { DashboardLoadingState } from "@/components/dashboard/dashboard-states";
import { AgingBugsTable, ReleaseBlockersTable, TestingProgressTable } from "@/components/dashboard/dashboard-tables";
import {
  DashboardChartCard,
  DistributionBarChart,
  DonutChart,
} from "@/components/dashboard/dashboard-visualizations";
import { EmptyState } from "@/components/qa/empty-state";
import { ErrorState } from "@/components/qa/error-state";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AutoRefreshStatus } from "@/components/dashboard/auto-refresh-status";
import { useActiveProject } from "@/shared/lib/use-active-project";
import { apiErrorMessage, caughtErrorMessage } from "@/shared/lib/api-error-message";
import { useDashboardRefresh } from "@/shared/lib/use-dashboard-refresh";
import type {
  DashboardAnalytics,
  DashboardFilterMetadata,
  DashboardTab,
} from "@/types/dashboard";
import { SystemDashboardsClient } from "@/components/dashboard/system-dashboard-client";
import { MyWorkbenchDashboardClient } from "@/components/dashboard/my-workbench-dashboard-client";

type DashboardState = {
  loading: boolean;
  error: string | null;
  data: DashboardAnalytics | null;
};

/** Auto-refresh cadence while the Dashboards page is open and idle. */
const AUTO_REFRESH_INTERVAL_MS = 5 * 60_000;
/** On returning to the tab, refresh immediately if the data is at least this old. */
const STALE_THRESHOLD_MS = 2 * 60_000;
/** Treat the user as "editing filters" for this long after their last change. */
const FILTER_SETTLE_MS = 1_500;

const emptyMetadata: DashboardFilterMetadata = {
  testPlans: [],
  testSuites: [],
  areas: [],
  iterations: [],
  workItemTypes: [],
  assignees: [],
};

const dashboardViews = {
  workbench: {
    label: "My Workbench",
    shortLabel: "Workbench",
    description: "Your assigned work, sprint priorities, and immediate delivery risks.",
    icon: BriefcaseBusiness,
  },
  project: {
    label: "Project Insights",
    shortLabel: "Project",
    description: "Release readiness, test execution, coverage, bugs, and blockers.",
    icon: BarChart3,
  },
  system: {
    label: "Platform Insights",
    shortLabel: "Platform",
    description: "Adoption and measurable time savings generated by iTestFlow.",
    icon: TrendingUp,
  },
} as const;

export function DashboardsClient() {
  const [activeDashboard, setActiveDashboard] = useState<"workbench" | "project" | "system">("workbench");
  const activeView = dashboardViews[activeDashboard];
  const ActiveViewIcon = activeView.icon;

  return (
    <Tabs id="dashboard-sections" value={activeDashboard} onValueChange={(value) => setActiveDashboard(value as "workbench" | "project" | "system")} className="content-stack">
      <div className="content-scroll-region pb-1">
        <TabsList variant="primary" aria-label="Dashboard view" className="grid h-auto w-full min-w-0 grid-cols-3 sm:inline-grid sm:w-fit sm:min-w-[640px]">
          {Object.entries(dashboardViews).map(([value, view]) => {
            const Icon = view.icon;
            return (
              <TabsTrigger key={value} value={value} className="h-11 px-2 py-2 duration-ui sm:px-3">
                <Icon className="size-4" aria-hidden="true" />
                <span className="sm:hidden">{view.shortLabel}</span>
                <span className="hidden sm:inline">{view.label}</span>
              </TabsTrigger>
            );
          })}
        </TabsList>
      </div>
      <section className="flex items-start gap-3" aria-live="polite">
        <div className="mt-0.5 rounded-lg border border-primary/20 bg-primary/10 p-2 text-primary">
          <ActiveViewIcon className="size-4" aria-hidden="true" />
        </div>
        <div className="min-w-0">
          <h2 className="text-lg font-semibold leading-6 text-foreground">{activeView.label}</h2>
          <p className="mt-0.5 text-sm leading-5 text-muted-foreground">{activeView.description}</p>
        </div>
      </section>
      <TabsContent value="workbench" forceMount hidden={activeDashboard !== "workbench"} className="space-y-4">
        <MyWorkbenchDashboardClient active={activeDashboard === "workbench"} />
      </TabsContent>
      <TabsContent value="project" forceMount hidden={activeDashboard !== "project"} className="space-y-4">
        <ProjectDashboardsClient active={activeDashboard === "project"} />
      </TabsContent>
      <TabsContent value="system" forceMount hidden={activeDashboard !== "system"} className="space-y-4">
        <SystemDashboardsClient active={activeDashboard === "system"} />
      </TabsContent>
    </Tabs>
  );
}

function ProjectDashboardsClient({ active }: { active: boolean }) {
  const scope = useActiveProject();
  const previousProjectId = useRef<string | null>(null);
  const bypassCacheRef = useRef(false);
  const [filters, setFilters] = useState<DashboardFilterState>(defaultDashboardFilters);
  const [state, setState] = useState<DashboardState>({ loading: true, error: null, data: null });
  const [activeTab, setActiveTab] = useState<DashboardTab>("testing");

  const requestBody = useMemo(() => ({
    scope,
    filters: {
      datePreset: filters.datePreset,
      from: filters.from || undefined,
      to: filters.to || undefined,
      testPlanId: filters.testPlanId,
      testSuiteIds: filters.testSuiteIds,
      areaPath: filters.areaPath,
      iterationPath: filters.iterationPath,
      workItemTypes: filters.workItemTypes,
      assignee: filters.assignee,
    },
  }), [filters, scope]);

  const {
    refreshToken,
    fetching,
    refreshFailed,
    setRefreshFailed,
    nextRefreshAt,
    triggerRefresh,
    markInteracting,
    beginFetch,
    settleFetch,
  } = useDashboardRefresh({
    enabled: active && Boolean(scope) && Boolean(state.data),
    loading: state.loading,
    intervalMs: AUTO_REFRESH_INTERVAL_MS,
    staleMs: STALE_THRESHOLD_MS,
    filterSettleMs: FILTER_SETTLE_MS,
    // The project dashboard forces a fresh build on any explicit refresh.
    onTrigger: () => { bypassCacheRef.current = true; },
  });

  useEffect(() => {
    const projectId = scope?.azureProjectId ?? null;
    if (projectId !== previousProjectId.current) {
      previousProjectId.current = projectId;
      setFilters(defaultDashboardFilters);
      setState({ loading: Boolean(scope), error: null, data: null });
      setActiveTab("testing");
    }
  }, [scope]);

  useEffect(() => {
    if (!active) return;
    if (scope === undefined) return;
    if (!scope) {
      setState({ loading: false, error: null, data: null });
      return;
    }
    const controller = new AbortController();
    void (async () => {
      // Capture and clear the project-only bypass-cache flag for exactly this attempt.
      const bypassCache = bypassCacheRef.current;
      bypassCacheRef.current = false;
      // A background (auto) refresh stays quiet: it never flips the full-page loading
      // state, so existing data and filters remain interactive while it runs.
      const background = beginFetch();
      if (!background) {
        setState((current) => ({ ...current, loading: true, error: null }));
      }
      try {
        const response = await fetch("/api/dashboard/analytics", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ ...requestBody, bypassCache }),
          signal: controller.signal,
          cache: "no-store",
        });
        const json = await response.json();
        if (!response.ok) throw new Error(apiErrorMessage(json, "Dashboard analytics failed."));
        setState({ loading: false, error: null, data: json as DashboardAnalytics });
        setRefreshFailed(false);
      } catch (error) {
        if (controller.signal.aborted) return;
        if (background) {
          // Keep the last good data on screen; surface a quiet, non-blocking notice.
          setRefreshFailed(true);
        } else {
          setState((current) => ({
            loading: false,
            error: caughtErrorMessage(error, "Dashboard analytics failed."),
            data: current.data,
          }));
        }
      } finally {
        if (!controller.signal.aborted) {
          settleFetch();
        }
      }
    })();
    return () => controller.abort();
  }, [active, requestBody, scope, refreshToken, beginFetch, settleFetch, setRefreshFailed]);

  // Applying a filter triggers its own fetch (which re-anchors the auto-refresh timer);
  // markInteracting also flags a short settle window so an auto-refresh never fires
  // mid-edit when the user is still adjusting controls.
  function handleFiltersChange(next: DashboardFilterState) {
    setFilters(next);
    markInteracting();
  }

  if (scope === undefined) return <DashboardLoadingState label="Loading project dashboard" cards={5} />;
  if (!scope) {
    return <EmptyState title="Select an Azure DevOps project" description="Use the project selector in the top bar to load testing progress, bugs, coverage, and release readiness." />;
  }

  const data = state.data;
  const metadata = data?.filterMetadata ?? emptyMetadata;
  const section = data?.metadata.sections;

  function refresh() {
    triggerRefresh(false);
  }

  function navigate(target: DashboardTab | "readiness") {
    if (target === "readiness") {
      scrollToDashboardSection("release-readiness");
      return;
    }
    setActiveTab(target);
    window.setTimeout(() => scrollToDashboardSection("dashboard-details"), 0);
  }

  return (
    <div className="content-stack" aria-busy={state.loading}>
      <DashboardFilters value={filters} effective={data?.filters} metadata={metadata} disabled={state.loading && !data} onChange={handleFiltersChange} />

      <ReportingScope
        projectName={scope.azureProjectName}
        data={data}
        filters={filters}
        metadata={metadata}
        loading={state.loading}
        refreshing={fetching}
        refreshFailed={refreshFailed}
        nextRefreshAt={nextRefreshAt}
        onRefresh={refresh}
      />

      {state.error ? <ErrorState title="Dashboard refresh failed" message={state.error} onRetry={refresh} /> : null}
      {data?.metadata.warnings.length ? <DataQualityNotice warnings={data.metadata.warnings} /> : null}

      {!data && state.loading ? <DashboardLoadingState label="Loading project insights" cards={5} /> : null}
      {data ? (
        <>
          <ReleaseReadinessCard data={data.releaseReadiness} />
          <DashboardKpiGrid data={data} loading={state.loading} onNavigate={navigate} />
          <ReleaseBlockersTable rows={data.releaseReadiness.blockers} onViewAll={() => navigate("blockers")} />

          <Tabs id="dashboard-details" tabIndex={-1} value={activeTab} onValueChange={(value) => setActiveTab(value as DashboardTab)} className="w-full min-w-0 scroll-mt-20 flex-col gap-4 outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2">
            <div className="content-scroll-region pb-1">
              <TabsList variant="primary" className="h-10 min-w-max shrink-0 justify-start border-border/80 bg-muted/60 p-1 shadow-none">
                <TabsTrigger value="testing" className="h-8 flex-none px-4">Testing Progress</TabsTrigger>
                <TabsTrigger value="bugs" className="h-8 flex-none px-4">Bug Status</TabsTrigger>
                <TabsTrigger value="blockers" className="h-8 flex-none px-4">Blockers</TabsTrigger>
              </TabsList>
            </div>

            <TabsContent value="testing" className="w-full min-w-0 space-y-4">
              {section?.testExecution.status !== "available" ? <SectionNotice message={section?.testExecution.message} /> : null}
              <DashboardChartCard title="Test Execution Status" description="Latest outcome for each selected Azure Test Plan point." hasData={hasValues(data.testingProgress.statusDistribution)} emptyMessage={section?.testExecution.message ?? "No test execution data is available."} summary={distributionSummary(data.testingProgress.statusDistribution)}>
                <DonutChart data={data.testingProgress.statusDistribution} centerLabel="Test points" />
              </DashboardChartCard>
              <TestingProgressTable rows={data.testingProgress.table} />
            </TabsContent>

            <TabsContent value="bugs" className="w-full min-w-0 space-y-4">
              {section?.bugs.status !== "available" ? <SectionNotice message={section?.bugs.message} /> : null}
              <DashboardChartCard title="Open Bugs by Severity" hasData={hasValues(data.bugStatus.bySeverity)} emptyMessage={section?.bugs.message ?? "No open bugs matched the selected filters."} summary={distributionSummary(data.bugStatus.bySeverity)}>
                <DistributionBarChart data={data.bugStatus.bySeverity} />
              </DashboardChartCard>
              <AgingBugsTable rows={data.bugStatus.agingBugs} />
            </TabsContent>

            <TabsContent value="blockers" className="w-full min-w-0 space-y-4">
              <ReleaseBlockersTable rows={data.releaseReadiness.blockers} title="All Release Blockers" maxRows={Number.POSITIVE_INFINITY} />
            </TabsContent>
          </Tabs>
        </>
      ) : null}
    </div>
  );
}

function ReportingScope({
  projectName,
  data,
  filters,
  metadata,
  loading,
  refreshing,
  refreshFailed,
  nextRefreshAt,
  onRefresh,
}: {
  projectName: string;
  data: DashboardAnalytics | null;
  filters: DashboardFilterState;
  metadata: DashboardFilterMetadata;
  loading: boolean;
  refreshing: boolean;
  refreshFailed: boolean;
  nextRefreshAt: number | null;
  onRefresh: () => void;
}) {
  const chips = scopeChips(filters, data, metadata);
  return (
    <section className="content-surface px-4 py-3">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
        <div className="min-w-0">
          <div className="text-xs font-medium uppercase tracking-normal text-muted-foreground">Reporting Scope</div>
          <div className="mt-0.5 truncate text-sm font-semibold text-foreground">{projectName}</div>
          <p className="mt-0.5 text-xs leading-5 text-muted-foreground">
            {data ? `Release health - ${formatDate(data.filters.dateRange.from)} to ${formatDate(data.filters.dateRange.to)}` : "Loading the selected Azure DevOps scope."}
          </p>
        </div>
        <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
          <div className="flex flex-wrap gap-1.5">{chips.map((chip, index) => <Badge key={`${index}-${chip}`} variant="secondary" className="font-normal">{chip}</Badge>)}</div>
          <div className="flex shrink-0 items-center gap-2">
            <AutoRefreshStatus generatedAt={data?.generatedAt} nextRefreshAt={nextRefreshAt} refreshing={refreshing} failed={refreshFailed} />
            <Button size="sm" variant="outline" onClick={onRefresh} disabled={loading}>
              <RefreshCw className={loading ? "size-4 animate-spin" : "size-4"} />Refresh
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
}

function DataQualityNotice({ warnings }: { warnings: string[] }) {
  const multiple = warnings.length > 1;
  return (
    <div className={`flex min-h-9 flex-col items-start gap-2 rounded-lg border px-3 py-2 text-sm sm:flex-row sm:items-center ${multiple ? "border-warning/35 bg-warning/10" : "border-primary/15 bg-primary/5"}`}>
      <AlertTriangle className={`size-4 shrink-0 ${multiple ? "text-warning" : "text-primary"}`} aria-hidden="true" />
      <p className="min-w-0 flex-1 leading-5 text-foreground">
        <span className="font-medium">Data limitation:</span> {warnings[0]}
      </p>
      <details className="group relative shrink-0">
        <summary className="cursor-pointer list-none rounded-md px-2 py-1 text-xs font-semibold text-primary outline-none hover:bg-primary/10 focus-visible:ring-2 focus-visible:ring-ring">
          <span className="sm:hidden">Details{multiple ? ` (${warnings.length})` : ""}</span>
          <span className="hidden sm:inline">View data quality details{multiple ? ` (${warnings.length})` : ""}</span>
        </summary>
        <div className="absolute right-0 z-20 mt-2 w-[min(420px,calc(100vw-2rem))] space-y-2 rounded-lg border border-border bg-popover p-3 text-popover-foreground shadow-lg">
          <div className="text-sm font-semibold">Data quality details</div>
          {warnings.map((warning) => (
            <div key={warning} className="rounded-md border border-warning/20 bg-warning/5 px-3 py-2">
              <p className="text-xs font-medium leading-5 text-foreground">{warning}</p>
              <p className="mt-1 text-xs leading-5 text-muted-foreground">{warningImpact(warning)}</p>
            </div>
          ))}
        </div>
      </details>
    </div>
  );
}

function SectionNotice({ message }: { message?: string }) {
  if (!message) return null;
  return <Alert><AlertTriangle className="size-4" /><AlertTitle>Partial data</AlertTitle><AlertDescription>{message}</AlertDescription></Alert>;
}

function scopeChips(filters: DashboardFilterState, data: DashboardAnalytics | null, metadata: DashboardFilterMetadata) {
  const chips = [datePresetLabel(data?.filters.dateRange.preset ?? filters.datePreset)];
  const suite = filters.testSuiteIds[0] ? metadata.testSuites.find((item) => item.value === filters.testSuiteIds[0])?.label : null;
  chips.push(suite ?? "All suites");
  if (filters.areaPath) chips.push(filters.areaPath);
  if (filters.iterationPath) chips.push(filters.iterationPath);
  if (filters.assignee) chips.push(metadata.assignees.find((item) => item.value === filters.assignee)?.label ?? filters.assignee);
  return chips.slice(0, 5);
}

function datePresetLabel(value: DashboardAnalytics["filters"]["dateRange"]["preset"]) {
  return { "7d": "Last 7 days", "14d": "Last 14 days", "30d": "Last 30 days", current_sprint: "Current sprint", custom: "Custom range" }[value];
}

function warningImpact(warning: string) {
  if (warning.toLowerCase().includes("execution history")) {
    return "Affected metric: execution trends. Older runs may be excluded; narrow the date range or increase the sync/run limit.";
  }
  if (warning.toLowerCase().includes("bug history")) {
    return "Affected metric: bug trends and reopened detection. Older work-item revisions may be excluded.";
  }
  return "Some dashboard metrics may be incomplete for the selected scope. Review the source configuration or narrow the filters.";
}

function hasValues(data: Array<{ value: number }>) {
  return data.some((item) => item.value > 0);
}

function distributionSummary(data: Array<{ name: string; value: number }>) {
  return data.map((item) => `${item.name}: ${item.value}`).join(". ");
}

function formatDate(value: string) {
  return new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(`${value}T00:00:00`));
}

function scrollToDashboardSection(id: string) {
  const element = document.getElementById(id);
  if (!element) return;
  const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  element.scrollIntoView({ behavior: reducedMotion ? "auto" : "smooth", block: "start" });
  window.setTimeout(() => element.focus({ preventScroll: true }), reducedMotion ? 0 : 250);
}
